<a href="https://colab.research.google.com/github/kartikvarma/Learning-ModelToAgent/blob/main/AI_And_ML_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 1**

## **Day 1**

1. **Tensors: The DNA of AI**

    Think of a Tensor as a multi-dimensional array (like a NumPy array) that can live on a GPU.

      *   A 0-D tensor is a scalar (a single number).
      *   A 1-D tensor is a vector.
      *   A 2-D tensor is a matrix.
      
      In AI, everything—images, words, or sounds—is converted into these numeric tensors.

2. **Autograd: The Magic of Learning**

    In the old days, you had to manually calculate the derivative (gradient) of your math functions to update model weights. PyTorch has Autograd. When you perform operations on tensors, PyTorch builds a computational graph. When you call .backward(), it automatically calculates the gradient of the loss with respect to every weight in your model.

3. **The Training Loop**

    Every model, from a simple line-recognizer to GPT-4, follows this loop:
      *  Forward Pass: Pass data through the model to get a prediction.
      *  Calculate Loss: Compare the prediction to the truth (How wrong are we?).
      *  Zero Grads: Clear out old math from the previous step.
      *  Backward Pass: Calculate the gradients (Backpropagation).
      *  Optimizer Step: Adjust the weights slightly to make the loss smaller.

### **Exercise1 : Setup and Tensor**

In [ ]:
import torch

# 1. Check if GPU is available (Colab free tier provides a T4 GPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 2. Create a Tensor (like a list of data)
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data).to(device) # Move it to the GPU!

# 3. Operations
y_data = x_data * 10
print(f"Original Tensor:\n{x_data}")
print(f"Multiplied Tensor on GPU:\n{y_data}")

# 4. The 'DNA' Check
print(f"Shape: {x_data.shape}")
print(f"Datatype: {x_data.dtype}")

Using device: cuda
Original Tensor:
tensor([[1, 2],
        [3, 4]], device='cuda:0')
Multiplied Tensor on GPU:
tensor([[10, 20],
        [30, 40]], device='cuda:0')
Shape: torch.Size([2, 2])
Datatype: torch.int64


### **Homework**

**Your Mission (1 Hour)**

1. Create a tensor of size (3, 3) filled with random numbers using torch.rand.
2. Move that tensor to the GPU.
3. Perform a matrix multiplication with another random tensor using torch.matmul().
4. Research: Look up what tensor.view() does and try to reshape a (4, 4) tensor into a (2, 8) tensor.

In [ ]:
### Solutions

# Create a tensor of size (3, 3) filled with random numbers using torch.rand.
rand_data3x3 = torch.rand(size=(3,3))

print(rand_data3x3)

# Move that tensor to GPU
x_rand_data3x3 = rand_data3x3.to(device)
print(f"Random Tensor on GPU:\n{x_rand_data3x3}")

# Perform a matrix multiplication with another random tensor using torch.matmul().

y_rand_data3x3 = x_rand_data3x3.matmul(torch.rand(size=(3,3)).to(device))

print(f"Multiplied Tensor on GPU:\n{y_rand_data3x3}")

# Research: Look up what tensor.view() does and try to reshape a (4, 4) tensor into a (2, 8) tensor.

ten4x4 = torch.randn(4,4).to(device)
v1 = ten4x4.view(2,8)

print(f"4 x 4 tensor:\n{ten4x4}")
print(f"Tensor view:\n{v1}")

# transpose
v2 = v1.transpose(-1,0)
print(f"Transpose -1, 0:\n{v2}")

tensor([[0.6408, 0.8711, 0.4876],
        [0.1061, 0.2869, 0.8692],
        [0.2540, 0.4483, 0.9407]])
Random Tensor on GPU:
tensor([[0.6408, 0.8711, 0.4876],
        [0.1061, 0.2869, 0.8692],
        [0.2540, 0.4483, 0.9407]], device='cuda:0')
Multiplied Tensor on GPU:
tensor([[1.4205, 0.5622, 1.4743],
        [0.9148, 0.2001, 0.5131],
        [1.1893, 0.3090, 0.8092]], device='cuda:0')
4 x 4 tensor:
tensor([[ 1.0621,  1.1766, -1.3085,  0.8364],
        [ 0.7854, -0.3924, -0.0378,  1.0239],
        [ 0.6343,  0.8679, -0.0635, -1.1109],
        [ 0.7507,  0.8340, -1.4883, -2.4339]], device='cuda:0')
Tensor view:
tensor([[ 1.0621,  1.1766, -1.3085,  0.8364,  0.7854, -0.3924, -0.0378,  1.0239],
        [ 0.6343,  0.8679, -0.0635, -1.1109,  0.7507,  0.8340, -1.4883, -2.4339]],
       device='cuda:0')
Transpose -1, 0:
tensor([[ 1.0621,  0.6343],
        [ 1.1766,  0.8679],
        [-1.3085, -0.0635],
        [ 0.8364, -1.1109],
        [ 0.7854,  0.7507],
        [-0.3924,  0.8340],
      